export const ToDoListTypes = {
    FETCH_TODOS_START: "FETCH_TODOS_START",
    FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
    FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",
    UPDATE_SORTS: "UPDATE_SORTS",
}