export const ToDoListsActionTypes = {
    ASYNC_ACTION_START: "ASYNC_ACTION_START",
    FETCH_LISTS_START: "FETCH_LISTS_START",
    FETCH_LISTS_SUCCESS: "FETCH_LISTS_SUCCESS",
    FETCH_LISTS_FAILURE: "FETCH_LISTS_FAILURE",
    ADD_TODO_START: "ADD_TODO_START",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
    REMOVE_TODO_START: "REMOVE_TODO_START",
    REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
    REMOVE_TODO_FAILURE: "REMOVE_TODO_FAILURE",
    UPDATE_TODO_START: "UPDATE_TODO_START",
    UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
    UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE"
}