export const ToDoActiontypes = {
    ADD_TODO: "ADD_TODO",
    FETCH_TODOS_BEGIN: "FETCH_TODOS_BEGIN",
    FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
    FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE"
};