export const FilterBarTypes = {
    SET_PREVIEW_LOADING: "SET_PREVIEW_LOADING",
    FETCH_FILTER_PREVIEW_START: "FETCH_FILTER_PREVIEW_START",
    FETCH_FILTER_PREVIEW_SUCCESS: "FETCH_FILTER_PREVIEW_SUCCESS",
    FETCH_FILTER_PREVIEW_FAILURE: "FETCH_FILTER_PREVIEW_FAILURE",
    CLEAR_FILTER_PREVIEW: "CLEAR_FILTER_PREVIEW"
}

