export const FilterBarTypes = {
    FETCH_FILTER_PREVIEW_START: "FETCH_FILTER_PREVIEW_START",
    FETCH_FILTER_PREVIEW_SUCCESS: "FETCH_FILTER_PREVIEW_SUCCESS",
    FETCH_FILTER_PREVIEW_FAILURE: "FETCH_FILTER_PREVIEW_FAILURE"
}

