export const ToDosActiontypes = {
    ASYNC_ACTION_BEGIN: "ASYNC_ACTION_BEGIN",
    ADD_TODO: "ADD_TODO",
    FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
    FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",
    REMOVE_TODO: "REMOVE_TODO",
    UPDATE_TODO: "UPDATE_TODO"
};