export const ToDosActiontypes = {
    ADD_FILTER: "APPLY_FILTER",
    ADD_TODO: "ADD_TODO",
    ASYNC_ACTION_BEGIN: "ASYNC_ACTION_BEGIN",
    DROP_TODO: "DROP_TODO",
    FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
    FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",
    REMOVE_FILTER: "REMOVE_FILTER",
    REMOVE_TODO: "REMOVE_TODO",
    UPDATE_SORTS: "UPDATE_SORTS",
    UPDATE_TODO: "UPDATE_TODO",
    
};