export const TodoContainerTypes = {
    ADD_TODO_START: "ADD_TODO_START",
    ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
    ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
    ASYNC_ACTION_BEGIN: "ASYNC_ACTION_BEGIN",
    FETCH_TODOS_START: "FETCH_TODOS_START",
    FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
    FETCH_TODOS_FAILURE: "FETCH_TODOS_FAILURE",
    REMOVE_FILTER: "REMOVE_FILTER",
    REMOVE_TODO_START: "REMOVE_TODO_START",
    REMOVE_TODO_SUCCESS: "REMOVE_TODO_SUCCESS",
    REMOVE_TODO_FAILURE: "REMOVE_TODO_FAILURE",
    TOGGLE_DETAILS: "TOGGLE_DETAILS",
    UPDATE_TODO_START: "UPDATE_TODO_START",
    UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
    UPDATE_TODO_FAILURE: "UPDATE_TODO_FAILURE",
    UPDATE_SORTS: "UPDATE_SORTS"
    
    
};